name: "Create a repository on personal account or organization"
description: "Creates a repository in the given user or organization account. Requires classic token with write access"

branding:
  icon: "box"
  color: "purple"

inputs:
  account:
    description: "String - Name of the account where the repository will be created"
    required: true
  name:
    description: "String - Name of repository to be created"
    required: true
  githubToken:
    description: "Your account's GitHub token"
    required: true
  description:
    description: "String - Description of repository to be created"
    required: false
    default: ""
  access:
    description: "Boolean - Is the repository private"
    required: false
    default: "false"
  visibility:
    description: "String - Access level ('private' or 'public')"
    required: false
    default: "public"
  issues:
    description: "Does the repository allows issues"
    required: false
    default: "false"

outputs:
  RepositoryURL:
    description: "String - URL of the created repository"
  RepositoryID:
    description: "String - Numeric representation of the repository"
runs:
  using: "node20"
  main: "runner/index.js"
